[tool.poetry]
name = "kyma-companion"
version = "0.1.0"
description = "Kyma Companion is AI Kyma assistant that helps you to manage your Kyma runtime"
authors = [
    "Muhammad Faizan muhammad.faizan@sap.com",
    "Aleksei Chernyshov aleksei.chernyshov@sap.com",
    "Carina Kothe carina.kothe@sap.com",
    "Friedrich Wilken jens.wilken@sap.com",
    "Tibor Kiss tibor.kiss01@sap.com",
    "Marco Bebway marco.bebway@sap.com",
    "Piotr Bochynski piotr.bochynski@sap.com",
    "Mansur Uralov m.uralov@sap.com",
]
readme = "README.md"
packages = [{ include = "src" }]
license = "Apache-2.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
# Add your production dependencies here
fastapi = "^0.111.0"
uvicorn = { extras = ["standard"], version = "^0.30.1" }
asgi-correlation-id = "^4.3.1"
pytest = "^8.2.2"
langchain-community = "^0.2.6"
hdbcli = "^2.21.26"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-mock = "^3.14.0"
pytest-asyncio = "^0.23.7"

[tool.poetry.group.dev.dependencies]
ruff = "v0.4.10"
flake8-bugbear = "^24.4.26"
poethepoet = "^0.27.0"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.poe.tasks]
lint = "ruff check ."
test = "pytest tests"
